### ISSUE TITLE
学长您好

### ISSUE THREAD

**Issue by Lucky-watermelon** [ambitiousCC/school_features#1]
学长您好：
  我通过您的哈哈镜项目，发现此复习仓库，请问您能否告知起算法设计与分析和机器学习课程考试时的考点。
  谢谢学长。
此致
  河大学弟

**Comment by ambitiousCC** [comment]
期末的时候，老师一般会划重点的，这个rep是开着玩的，考点已经过时了。
建议找你的大一届学长学姐。
此致
学弟贴贴

**Comment by Lucky-watermelon** [comment]
好的，谢谢学长

**Comment by Lucky-watermelon** [comment]
学长已经读博了啊，我现在也读研了。
祝学长读博顺利！
